/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package intrepion.greeting.json.rpc.server.kotlin.javalin

import io.javalin.Javalin

fun main() {
    val app = Javalin.create {
        it.plugins.enableCors {cors ->
            cors.add {
                it.allowHost("http://localhost:3000/")
            }
        }
    }
    .post("/api") { ctx -> ctx.result("Hello World") }
    .start(7070)
}
